### ISSUE TITLE
Can not use CMD_OAUTH2_PROVIDERNAME to override provider name

### ISSUE THREAD

**Issue by AlexM4H** [libnewton/hedgenext-server#1]
first of all, thank you for your project. We have been looking for something like this for a while... :-)

We would like to adapt the provider name to our Nextcloud. 

PS: Maybe we can meet at some point in Berlin.

I am a member of Open Source Ecology Germany e. V. (ose-germany.de)

Best regards
Alexander

**Comment by libnewton** [comment]
Hi Alex,
thanks for the feedback! Unfortunately as someone from NRW I cannot easily jump to Berlin, but thanks for your invitation nevertheless!

Regarding the CMD_OAUTH2_PROVIDERNAME:
There is really only one provider, which is the connected Nextcloud. Thus, login is usually performed automatically without the user having to do anything. 
Only exception is the login button on the page, where currently a modal is shown with the only option possible (Nextcloud). I'll probably make this modal obsolete as well and just straight up redirect to NC for login.
