### ISSUE TITLE
SSO via Keycloak or similar does not work

### ISSUE THREAD

**Issue by AlexM4H** [libnewton/hedgenext-server#2]
It seems that only the login via Nextcloud works.

Since we are using another SSO provider (Keycloak), it would be nice to be able to continue using it.

**Comment by libnewton** [comment]
Hi,
indeed, this functionality has been removed. Actually, all login mechanisms have been removed. Login is automatically done via Nextcloud (hedgenext Nextcloud App needed).
Reason is to reduce the codebase and also the attack surface by enforcing a streamlined Hedgedoc experience.

If you need SSO, you can just use Keycloak with Nextcloud, i.e. make them login into Nextcloud using SSO. That works with https://apps.nextcloud.com/apps/oidc_login for example.

If you do not need the Nextcloud part, I can highly recommend just sticking with the original Hedgedoc.
