### ISSUE TITLE
Import existing Hedgedoc documents into Nextcloud

### ISSUE THREAD

**Issue by AlexM4H** [libnewton/hedgenext-server#3]
Is there currently an easy way to convert existing Hedgedoc documents to HedgeNext documents and transfer them to the Nextcloud?

Is such an import function in planning?

**Comment by libnewton** [comment]
hi , yes you can just use your existing hedgedoc database and apply the new migrations. this should happen automatically when starting hedgedoc. besides that old hedgedoc documents are not linked from inside the nextcloud
